travis:
  secure:
    BINSTAR_TOKEN: Znx0E042u1z/JE905ubPz7zjwrixb9SZxTIfYFGhilkaC7CbNMCvq3o47F6DFxcjf3Gxc8glAa6vHZ9qwY68O7UxacWUx7cXqCyzJjm214MYcCx1XbRptMrlaS0UOdqA2Qb4rD7942kagsIcXDrFi+gHzCvcT2Gn/29NJ8zAfoh3e4KSNUhROmfWV65UzdkrMkLiKcoJnCbRmPk6DnTC9X6s4rbXmpf+ETAlv009nipyk8J0++xb4qFruhummtLDMrvLgLNmhRMTTHnIPjhnZDPv4vRG/nzWRUn+Qby3C3t47EVCABg7S8aRZ6D3FKoq7oJSn82vglCoy7hFHUL+ftjjkHGX3RDZhWKp2L4ees1HrluQM4gt0Xq5jWvyPLhwZg7rLoJlF4s7n0eXzX+25rPO6N6E+9XMGKxHjIQ0ZTkHK5uj/ksdlaYsW/W3wsNA5PXFbh9g3lZp+QonRKqNo+yeGGkBakS5RYP4gBsdQ/yQLz2EGLYxAyxu8JThFDdv+oYX9SELGuxJeJFg1od4Jd87xgcf56Yx8pOOVme7MkdpSpSthZ9LOALEaXX4ExqceFPTTJedS13LjJDFQe0Nt6agA5JPiYEtFKQFvB4vyoV16p3yAzuKrQE3w6R455O2Mw87YDzQEuJ8iBxevWDCGIOBRQtetZSzX85sEtEjJxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
